# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [137]:
from scipy import stats 
import numpy as np

In [138]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [139]:
from scipy.stats import ttest_1samp

In [140]:
## Method1 
t_statistic, p_value = ttest_1samp(GPU1, 0)
print("t_statistics of GPU1 is : ", t_statistic)
print("p-value of GPU1 is : ", p_value)
print("Since p-value < 0.05, hence null hypothesis : mean is equal to 0, is rejected")

t_statistics of GPU1 is :  34.056241516158195
p-value of GPU1 is :  7.228892044970457e-15
Since p-value < 0.05, hence null hypothesis : mean is equal to 0, is rejected


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [141]:
from scipy.stats import ttest_ind
t_statistic, p_value = ttest_ind(GPU1, GPU2)
print("two-sample t-test t-stat is : ", t_statistic)
print("two-sample t-test p-value is : ", p_value)

print ("two-sample t-test p_value < 0.05, hence GPU1 and GPU2 don't have the same mean and same variance.")
print ("Hence, alternate hypothesis : There is a significant difference, is accepted and Null hypothesis is rejected.")

two-sample t-test t-stat is :  -2.627629513471839
two-sample t-test p-value is :  0.013794282041452725
two-sample t-test p_value < 0.05, hence GPU1 and GPU2 don't have the same mean and same variance.
Hence, alternate hypothesis : There is a significant difference, is accepted and Null hypothesis is rejected.


## Question 3

He is trying a third GPU - GPU3.

In [2]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

NameError: name 'np' is not defined

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [143]:
#Null Hypothesis : There is no significant difference between data sets
#Alternate Hypothesis : There is a significant difference

t_statistic, p_value = ttest_ind(GPU1, GPU3)
print("two-sample t-test t-stat is : ", t_statistic)
print("two-sample t-test p-value is : ", p_value)
print ("two-sample t-test p_value > 0.05, hence fail to reject the null hypothesis : There is no significant difference between data sets between GPU1 and GPU3 data sets.")

two-sample t-test t-stat is :  -1.4988943759093303
two-sample t-test p-value is :  0.14509210993138993
two-sample t-test p_value > 0.05, hence fail to reject the null hypothesis : There is no significant difference between data sets between GPU1 and GPU3 data sets.


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [3]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [145]:
from scipy.stats import levene
t_statistic, p_value = levene(e1,e2,e3)
print("three-sample levene t-stat is : ", t_statistic)
print("three-sample levene p-value is : ", p_value)
print("since p-value > 0.05, hence fail to reject the null hypothesis that all samples are from population with equal variance")

three-sample levene t-stat is :  2.6741725711150446
three-sample levene p-value is :  0.12259792666001798
since p-value > 0.05, hence fail to reject the null hypothesis that all samples are from population with equal variance


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [146]:
t_statistic, p_value = stats.f_oneway(e1,e2,e3)
print("One way ANOVA statistic is : ", t_statistic)
print("One way ANOVA p-value is : ", p_value)
print("since p-value > 0.05, hence fail to reject the null hypothesis that e1, e2, e3 have the same population mean")

One way ANOVA statistic is :  2.51357622845924
One way ANOVA p-value is :  0.13574644501798466
since p-value > 0.05, hence fail to reject the null hypothesis that e1, e2, e3 have the same population mean


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*


In [147]:
## TypeI error : When null hypothesis is TRUE, but rejected.   
## TypeII error : When null hypothesis is FALSE, but not rejected. Failed to accept the Alternate Hypothesis.    

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.



In [148]:
## Null Hypotheis : Mean Waiting Time = 4.5 minutes
## Alternative Hypotheis : Mean Waiting Time <> 4.5 minutes    

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [149]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [150]:
t_statistic, p_value, dof_value, contigency_table = stats.chi2_contingency(dice)
print("chi2 stat is : ", t_statistic)
print("p-value is : ", p_value)
print("degree of freedom is : ", dof_value)
print("contingency is : ", contigency_table)

chi2 stat is :  23.315671914716496
p-value is :  0.07766367301496693
degree of freedom is :  15
contingency is :  [[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [151]:
z_score = stats.zscore(dice)
z_score

array([[-0.46291005, -0.18884739, -1.83711731,  1.44115338],
       [ 1.38873015, -0.64208114,  1.22474487,  0.        ],
       [ 0.9258201 ,  0.7176201 ,  0.61237244, -1.44115338],
       [-0.9258201 ,  1.62408759,  0.61237244, -0.96076892],
       [-1.38873015,  0.03776948,  0.        ,  0.        ],
       [ 0.46291005, -1.54854863, -0.61237244,  0.96076892]])

In [152]:
p_value = stats.norm.sf(z_score)
p_value

array([[0.67828558, 0.57489379, 0.96690371, 0.07477068],
       [0.08245741, 0.73958975, 0.11033568, 0.5       ],
       [0.17726974, 0.23649578, 0.27014569, 0.92522932],
       [0.82273026, 0.05217856, 0.27014569, 0.83166582],
       [0.91754259, 0.48493574, 0.5       , 0.5       ],
       [0.32171442, 0.93925487, 0.72985431, 0.16833418]])

In [153]:
p_value.mean()

0.49478056512575197

## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [154]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [155]:
t_statistic, p_value = stats.ttest_rel(before,after)
print("t_statistics is : ", t_statistic)
print("p-value is : ", p_value)
print("Since p-value < 0.05, hence we reject the null hypothesis : weight loss drug works")
print("Before and After samples don't have identical average")

t_statistics is :  6.005197426479002
p-value is :  3.6835248825579786e-09
Since p-value < 0.05, hence we reject the null hypothesis : weight loss drug works
Before and After samples don't have identical average
